### ISSUE TITLE
In iOS Data Persists after uninstalling the application 

### ISSUE THREAD

**Issue by kotlincodes** [mogol/flutter_secure_storage#243] opened 2021-06-22 15:39 UTC
Hi,

I am using this plugin and found that the Data stored are persisting after uninstalling the application from the device. In android data gets cleared after uninstall but in **iOS** it persists. How can I resolve this issue, I need to clear all the stored data once app is uninstalled from the **iOS** device.

Details

Device : iOS simulator -iOS 7 plus
flutter_secure_storage : 4.2.0

Expecting a Solution ASAP. Thanks.

**Comment by raphagodoi** [comment] 2021-07-28 16:33
Same here

**Comment by juliansteenbakker** [comment] 2021-07-29 09:14
Duplicate of #125

**Closed by juliansteenbakker** 2021-07-29 09:14 UTC
