### ISSUE TITLE
Update flutter_secure_storage_web depends on js ^0.6.3

### ISSUE THREAD

**Issue by MarceloRab** [mogol/flutter_secure_storage#683] opened 2024-02-23 17:10 UTC
Firstly, thank you for your work.

I'm having difficulty importing packages due to the broken js version.

I thank the attention.

`Because socket_io_client >=3.0.0-beta.0 depends on js ^0.7.1 and every version of flutter_secure_storage_web depends on js ^0.6.3, socket_io_client >=3.0.0-beta.0 is incompatible with flutter_secure_storage_web.`

**Comment by ThexXTURBOXx** [comment] 2024-02-28 12:45
The `js` version is not broken, it's just outdated. #680 fixes this.
Also, this issue is a duplicate of #670

**Comment by noskova** [comment] 2024-03-25 19:19
+1

**Comment by andremobiis** [comment] 2024-03-26 18:01
+1

**Comment by ThexXTURBOXx** [comment] 2024-03-26 18:05
Commenting "+1" does not add anything here. If you want to stay up to date regarding this issue, subscribe to this issue instead

**Comment by vongrad** [comment] 2024-04-14 07:22
+1

**Closed** 2024-05-08 14:55 UTC

**Comment by mark8044** [comment] 2024-05-19 19:57
@juliansteenbakker Although closed, this seems to still be an issue.  It looks like its because flutter_secure_storage 9.2.1 depends on flutter_secure_storage_web ^1.2.1 which still contains the js dependency.  Perhaps that should be updated as well

**Comment by ThexXTURBOXx** [comment] 2024-05-20 08:38
@mark8044 This is desired behaviour. See this comment for reference: https://github.com/mogol/flutter_secure_storage/pull/698#issuecomment-2111967218
