### ISSUE TITLE
Numerous deprecations

### ISSUE THREAD

**Issue by 0biWanKenobi** [mogol/flutter_secure_storage#172] opened 2020-10-19 09:02 UTC
Building on Android 10 results in a number of deprecations:

```
fluttersecurestorage\ciphers\RSACipher18Implementation.java:131: warning: [deprecation] locale in Configuration has been deprecated
        config.locale = locale;
              ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:132: warning: [deprecation] updateConfiguration(Configuration,DisplayMetrics) in Resources has been deprecated
        resources.updateConfiguration(config, resources.getDisplayMetrics());
                 ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:150: warning: [deprecation] KeyPairGeneratorSpec in android.security has been deprecated
                spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                                           ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:150: warning: [deprecation] Builder in KeyPairGeneratorSpec has been deprecated
                spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                                                                ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:150: warning: [deprecation] Builder(Context) in Builder has been deprecated
                spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                       ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:151: warning: [deprecation] setAlias(String) in Builder has been deprecated
                        .setAlias(KEY_ALIAS)
                        ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:152: warning: [deprecation] setSubject(X500Principal) in Builder has been deprecated
                        .setSubject(new X500Principal("CN=" + KEY_ALIAS))
                        ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:153: warning: [deprecation] setSerialNumber(BigInteger) in Builder has been deprecated
                        .setSerialNumber(BigInteger.valueOf(1))
                        ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:154: warning: [deprecation] setStartDate(Date) in Builder has been deprecated
                        .setStartDate(start.getTime())
                        ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:155: warning: [deprecation] setEndDate(Date) in Builder has been deprecated
                        .setEndDate(end.getTime())
                        ^
fluttersecurestorage\ciphers\RSACipher18Implementation.java:156: warning: [deprecation] build() in Builder has been deprecated
                        .build();
```

**Comment by juliansteenbakker** [comment] 2021-07-29 07:43
Duplicate of #162

**Closed by juliansteenbakker** 2021-07-29 07:43 UTC
