### ISSUE TITLE
[bug] [macOS]: Creates duplicate entries when `write` with a key is used

### ISSUE THREAD

**Issue by buehler** [mogol/flutter_secure_storage#573] opened 2023-05-31 13:59 UTC
With the current version (8.0.0), and the initialisation is done as follows:

```dart
FlutterSecureStorage(
        iOptions: IOSOptions.defaultOptions.copyWith(
            accountName: '${env.appType} App Secure Storage',
            accessibility: KeychainAccessibility.unlocked_this_device,
            synchronizable: false),
        mOptions: MacOsOptions.defaultOptions.copyWith(
            accountName: '${env.appType} App Secure Storage',
            accessibility: KeychainAccessibility.unlocked_this_device,
            synchronizable: false));
```

The storage creates duplicate keychain entries. This results in the wrong value being read when accessing the values and thus creates issues with access/refresh tokens for OIDC.

Currently we use refresh tokens to fetch new access tokens for users. After the first write (which creates a keychain entry in the iCloud keychain), the correct value is read. When the refresh happens, the same method (write) is used. This creates a second entry in the "login" keychain on macOS which duplicates the value in the keychain. The read query then finds the iCloud one first and only ever returns this value. One does not get access to the correct access.

![image](https://github.com/mogol/flutter_secure_storage/assets/1067213/32a6931b-bd4a-4303-ac76-eb3fda305968)

This results in weird behaviour during login sessions.

I tried to search for the code that is creating this issue but I do not get the concept of the macOS keychain in obj-c.

One workaround for now is: always delete the key first before writing.

```dart
await _secureStorage.delete(key: _accessTokenKey);
await _secureStorage.write(key: _accessTokenKey, value: accessToken);
```

However, according to the documentation, this should not be the case (as far as I know) ;-)

Can someone confirm this or point me into the right direction? :-)

Regards

**Comment by tomekit** [comment] 2023-07-25 11:27
I was wondering if you managed to get to the root cause of this. We're also experiencing duplicate entries in the keychain.

**Comment by buehler** [comment] 2023-07-25 11:43
Sadly no, I have no to very little experience in macOS / iOS native coding. Since I wrote my own service around the secure storage, it was not a big issue, we just use the workaround.

**Comment by bvoq** [comment] 2023-08-04 09:14
I've noticed this too. Another workaround:
If you set `synchronizable: true` in the macOsOptions it will only write to either 'Local Items' or 'iCloud Items' if iCloud Keychain is enabled for your user.

```
MacOsOptions(
  accessibility: KeychainAccessibility.unlocked_this_device,
  groupId: null,
  // Note: This needs to be true in order for macOS to only write to the Local Items (or Cloud Items) keychain.
  synchronizable: true,
);
```

**Comment by juliansteenbakker** [comment] 2024-08-13 20:17
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 20:17 UTC
