### ISSUE TITLE
FlutterSecureStoragePlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by BringTheChill** [mogol/flutter_secure_storage#234] opened 2021-04-30 11:02 UTC
`Note: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-4.2.0\android\src\main\java\com\it_nomads\fluttersecurestorage\FlutterSecureStoragePlugin.java uses or overrides a deprecated API.
`

**Comment by DieterHolvoet** [comment] 2021-05-01 20:08
More info:
```
/Users/dieter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java:131: warning: [deprecation] locale in Configuration has been deprecated
        config.locale = locale;
              ^
/Users/dieter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java:132: warning: [deprecation] updateConfiguration(Configuration,DisplayMetrics) in Resources has been deprecated
        resources.updateConfiguration(config, resources.getDisplayMetrics());
                 ^
/Users/dieter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java:150: warning: [deprecation] KeyPairGeneratorSpec in android.security has been deprecated
                spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                                           ^
/Users/dieter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java:150: warning: [deprecation] Builder in KeyPairGeneratorSpec has been deprecated
                spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                                                                ^
4 warnings
```

**Comment by davidhsoftware** [comment] 2021-05-06 06:26
Same as #162

**Comment by sumitsharansatsangi** [comment] 2021-05-07 05:06
I also received this error in the version 4.2

**Comment by BringTheChill** [comment] 2021-05-10 13:34
> I also received this error in the version 4.2

It's not an error

**Comment by BringTheChill** [comment] 2021-05-20 09:56
@mogol any news?

**Comment by nirbar89** [comment] 2021-06-06 20:02
@mogol any news?

**Comment by piotritagsolutions** [comment] 2021-06-07 06:59
The same for me

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

**Comment by flutterq2** [comment] 2021-06-25 01:54
All Possible working solution here [[Solved] FlutterFirebaseCorePlugin.java uses or overrides a deprecated API](https://fluttercorner.com/solved-flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api/)

**Comment by piotritagsolutions** [comment] 2021-06-25 05:44
This is not a solution:
1. Don’t use Firebase
2. minds 25, target 30



On 25 Jun 2021, at 03:54, flutterq2 ***@***.******@***.***>> wrote:



All Possible working solution here [Solved] FlutterFirebaseCorePlugin.java uses or overrides a deprecated API<https://fluttercorner.com/solved-flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api/>

**Comment by juliansteenbakker** [comment] 2021-07-29 08:15
Duplicate of #162

**Closed by juliansteenbakker** 2021-07-29 08:15 UTC

**Comment by tr1ms** [comment] 2021-09-30 10:59
I have the same issue

**Comment by piotritagsolutions** [comment] 2021-09-30 11:38
Because reasons is AsyncTask

**Comment by ignacioContalive** [comment] 2022-07-04 21:15
I had the same issue and the reason was the flutter secure storage package version is lower than minSdk 23

So, the solution was:

1. `flutter pub outdated` to visualize dependencies with low version
2. `flutter pub upgrade --major-versions` to upgrade that dependencies

**Comment by markusramsak** [comment] 2022-08-24 16:56
Deprecation warning still exists. Would this please be solved?

**Comment by Yogabayu** [comment] 2022-11-07 08:09
any solution abaout this ?

**Comment by luis8elias** [comment] 2022-11-07 17:18
still no solution?

**Comment by Manmapi** [comment] 2022-11-24 03:27
Any solution on this problem?
