### ISSUE TITLE
PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by Yongle-Fu** [mogol/flutter_secure_storage#248] opened 2021-07-13 02:33 UTC
flutter_secure_storage: 4.2.0

Android 11
M2102K1C  1050

Crashed in non-app: message_codecs.dart in StandardMethodCodec.decodeEnvelope within flutter
flutter_secure_storage.dart in FlutterSecureStorage.read at line 50 within flutter_secure_storage
Called from: <asynchronous suspension>
flutter_secure_storage.dart in FlutterSecureStorage.containsKey at line 71 within flutter_secure_storage

PlatformException
PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:143)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$400(FlutterSecureStoragePlugin.java:30)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:200)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by 142hitesh** [comment] 2021-07-16 08:38
Facing same issue

**Comment by juliansteenbakker** [comment] 2021-07-29 08:19
Closing this as duplicate of #210

**Comment by NamanShergill** [comment] 2021-08-07 11:10
> 
> 
> Closing this as duplicate of #210

Why close this issue as a duplicate of a CLOSED issue when the problem is still ongoing and not fixed?

**Comment by juliansteenbakker** [comment] 2021-08-07 11:12
My bad, i thought it was open.

**Comment by nombrekeff** [comment] 2021-09-06 09:40
Hey, how's this issue going? I'm facing the issue and have not found any fix or workaround yet!

**Comment by dakr0013** [comment] 2021-09-06 09:56
@nombrekeff adding custom backup rules fixed the error for me:
1. i added `android:fullBackupContent="@xml/my_backup_rules"` to application tag in AndroidManifest.xml
2. i created the file `my_backup_rules.xml` with following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <include domain="sharedpref" path="."/>
    <exclude domain="sharedpref" path="FlutterSecureStorage"/>
</full-backup-content>
```

see also https://pub.dev/packages/flutter_secure_storage#configure-android-version and https://developer.android.com/guide/topics/data/autobackup#IncludingFiles

**Comment by nombrekeff** [comment] 2021-09-06 10:00
@dakr0013 thanks, I will try that! I've seen this solution a lot, so everything points that it works!

**Comment by nombrekeff** [comment] 2021-10-14 09:14
The solution @dakr0013 told me did not work for me, I'm still facing the issue. Any updates on this?

**Comment by dala00** [comment] 2021-11-10 07:34
I temporary fixed. First, readAll always throws exception. So use read only.

And when a key doesn't exist, exception is thrown. So catch.

```dart
    try {
      return await storage.read(key: myKey);
    } catch (e) {
      return null;
    }
```

**Closed** 2021-11-12 14:06 UTC

**Comment by novas1r1** [comment] 2021-12-06 14:52
Still the same issue with Pixel4a Android 12 and flutter_secure_storage 5.0.2

"PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT"

**Comment by fede1295** [comment] 2021-12-16 09:20
Same issue for me .. please reopen the ticket and fix it

**Comment by shubham-vunet** [comment] 2021-12-23 10:51
> Same issue for me .. please reopen the ticket and fix it

+1
