### ISSUE TITLE
flutter_secure_storage_windows doesn't work

### ISSUE THREAD

**Issue by florian-lefebvre** [mogol/flutter_secure_storage#290] opened 2021-08-16 14:40 UTC
I updated my app to use the last prerelease version of `flutter_secure_storage` (`5.0.0-beta.3`). But it doesn't work.
The first time I execute `flutter run -v`, I get the following:
```bash
[ +189 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device Windows... (completed in 232ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[ +353 ms] Flutter run key commands.
[   +2 ms] r Hot reload.
[   +1 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety
[   +1 ms] An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:52830/BDIhwgVtuqU=/
[  +18 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///C:/Users/Admin/AppData/Local/Temp/ynotes89f5519b/ynotes/)
[ +263 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 50 095ms.
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```
And when I launch a second time, I get:
```bash
[ +549 ms] Caching compiled dill
[  +48 ms] Connecting to service protocol: http://127.0.0.1:53045/N5Suwh8kuDU=/
[ +260 ms] Fail to connect to service protocol: http://127.0.0.1:53045/N5Suwh8kuDU=/: HttpException: Connection closed before full header was
received, uri = http://127.0.0.1:53045/N5Suwh8kuDU=/ws
[   +4 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:53045/N5Suwh8kuDU=/
[   +4 ms] "flutter run" took 23 159ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +8 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2
```
I think it's linked to the beta version because when I switch to `^4.2.1`, I get the error that says that the plugin can't be used because it's not made for windows.

I've setup everything correctly (Visual Studio etc), I don't have any issue when running `flutter doctor -v`. I'm on Windows 10.

Here is the project link if you want to see: https://github.com/florian-lefebvre/ynotes/tree/test/windows

**Comment by juliansteenbakker** [comment] 2021-08-17 12:53
flutter_secure_store 4.2.1 doesn't have support for windows so that won't work. It almost looks like it has more to do with Flutter rather than this plugin. I don't have a Windows pc to test it on right now.

**Comment by florian-lefebvre** [comment] 2021-08-17 13:20
Yes I know that 4.2.1 doesn't have support for windows but that was only to show that the beta version is responsible for the error.

**Comment by florian-lefebvre** [comment] 2021-08-17 13:20
How can I help you debug this issue ?

**Comment by juliansteenbakker** [comment] 2021-08-18 07:25
Like i said i don't have a windows PC right now. Maybe @kennethnym can take a look.

**Comment by kennethnym** [comment] 2021-08-19 18:23
@florian-lefebvre are you able to reproduce this issue in a brand-new project?

**Comment by florian-lefebvre** [comment] 2021-08-19 18:26
I haven't tried but I'll will and I'll let you know the result.
Just in case, it's not only related to my computer, @JsonLinesCode has the same issue on a beta Win 11 brand new pc.

**Comment by JsonLinesCode** [comment] 2021-08-20 09:38
Looks like #287 is not solved yet. 
I've just created a brand-new project and just called `String? test = storage.read(key: "someKey");`; and the app crashes if the key doesn't exist.

**Comment by juliansteenbakker** [comment] 2021-08-20 09:41
Just realised #288 is merged but not published yet. I will create a new release right now.

**Comment by juliansteenbakker** [comment] 2021-08-20 09:49
Please try again with v5.0.0-beta.4 @JsonLinesCode @florian-lefebvre

**Comment by JsonLinesCode** [comment] 2021-08-20 10:20
> 
> 
> Please try again with v5.0.0-beta.4 @JsonLinesCode @florian-lefebvre

We were directly using secure_storage from github ref... so it just checked with beta.4 and it didn't change anything.

**Comment by juliansteenbakker** [comment] 2021-08-20 10:21
Ah that i did not know. I hope someone else with a windows PC is able to debug this.

**Comment by Jon-Salmon** [comment] 2021-11-09 19:20
I've been unable to reproduce this issue in a fresh flutter project using 5.0.0-beta.5

Reading the error log posted above, that doesn't seem to relate to this plugin at all, although I might be wrong.

**Closed** 2021-11-12 15:08 UTC
Labels: bug, help wanted, windows
