### ISSUE TITLE
No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage

### ISSUE THREAD

**Issue by eliasjtg** [mogol/flutter_secure_storage#289] opened 2021-08-13 21:25 UTC
![image](https://user-images.githubusercontent.com/22435698/129418193-201db729-cec8-4b49-8328-0bee4624cc31.png)
![image](https://user-images.githubusercontent.com/22435698/129418245-89d75720-99f9-4a3a-bed9-f4fdb893a956.png)
![image](https://user-images.githubusercontent.com/22435698/129418367-24e85b5c-1085-43a4-aa24-2eb75df76f49.png)

My app is created with fresh install with android embedded v2

![image](https://user-images.githubusercontent.com/22435698/129419802-84db8775-250f-4bc7-aa80-025eeeef99f7.png)

**Comment by juliansteenbakker** [comment] 2021-08-18 07:28
Which device are you getting this error on? And which version of the package are you using?

**Comment by juliansteenbakker** [comment] 2021-08-18 08:59
I'm closing this as duplicate of #152

**Closed by juliansteenbakker** 2021-08-18 08:59 UTC
Labels: bug, question

**Comment by eliasjtg** [comment] 2021-08-18 13:26
Redmi Note 8 (mobile)  • 17eba2c2   • android-arm64  • Android 10 (API 29)
moto g 7 plus (mobile) • ZY225G7TW3 • android-arm64  • Android 10 (API 29)
 
 flutter_secure_storage: ^4.2.1

**Comment by eliasjtg** [comment] 2021-08-18 13:26
Maybe it's a duplicate but i don't see progress in issue 152

**Comment by lchenneberg** [comment] 2021-08-20 17:35
I have the same issue.

**Comment by eliasjtg** [comment] 2021-08-23 20:00
:/
