### ISSUE TITLE
[Question] Will there ever be synchronous functions

### ISSUE THREAD

**Issue by michaelessiet** [mogol/flutter_secure_storage#510] opened 2023-01-22 02:13 UTC
Hi, I am wondering if their will ever be synchronous read and write functions. I'm currently facing an issue where I need a write to finish before running my app but for some reason it doesn't finish

**Comment by dJani97** [comment] 2023-01-31 20:47
I don't think so. File operations should be asynchronous by design. [Hive](https://pub.dev/packages/hive), for example, archives synchronous reads and writes by caching in memory, which does not guarantee that the written data is immediately written to persistent storage.

You can have an `async main` method which ensures that your write will finish before the app runs:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await myAsyncWriteMethod();

  runApp( ... );
}
```

The app will keep showing the splash screen until all async operations are finished and `runApp()` is called.

**Comment by juliansteenbakker** [comment] 2024-08-13 20:07
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 20:07 UTC
