### ISSUE TITLE
Android 4.4.2: MissingPluginException(No implementation found for method write on cannel plugins.it_nomads.com/flutter_secure_storage))

### ISSUE THREAD

**Issue by yousifAlneamy** [mogol/flutter_secure_storage#118] opened 2020-04-23 12:52 UTC
Read and write not working when tested on Samsung Grand 2. I had the same problem with other devices (Reported by users)

I have tried `stable` and `beta` channels

**flutter doctor -v**

```
✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-IQ)
    • Flutter version 1.17.0 at /Users/yousif/development/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yousif/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by hmawla** [comment] 2020-06-01 15:13
Check here #131

**Comment by gianlucainnocente** [comment] 2020-08-07 14:09
Same problem with v3.3.3

**Comment by juliansteenbakker** [comment] 2021-07-27 20:55
Duplicate of #71

**Closed by juliansteenbakker** 2021-07-27 20:55 UTC
