### ISSUE TITLE
exception in rtl locale , can not parse date time formate in init

### ISSUE THREAD

**Issue by mr-mamali** [mogol/flutter_secure_storage#143] opened 2020-07-10 08:27 UTC
when locale is ltr all things works fine , but when locale of android system is an rtl language , this exception occured and can not parse date time format.

**W/art     ( 9639): Unresolved exception class when finding catch block: android.security.keystore.StrongBoxUnavailableException
E/FlutterSecureStoragePl( 9639): Registration failed
E/FlutterSecureStoragePl( 9639): java.lang.IllegalArgumentException: invalid date string: Unparseable date: "òðð÷ñððøñ÷òøGMT+00:00" (at offset 0)**
E/FlutterSecureStoragePl( 9639): 	at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:98)
E/FlutterSecureStoragePl( 9639): 	at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:62)
E/FlutterSecureStoragePl( 9639): 	at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.setNotBefore(X509V3CertificateGenerator.java:112)
E/FlutterSecureStoragePl( 9639): 	at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:127)
E/FlutterSecureStoragePl( 9639): 	at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.b.a.a(:157)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.b.a.b(:115)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.b.a.<init>(:33)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.b.b.<init>(:31)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.a.a(:45)
E/FlutterSecureStoragePl( 9639): 	at g.c.a.a.onAttachedToEngine(:56)
E/FlutterSecureStoragePl( 9639): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(:133)
E/FlutterSecureStoragePl( 9639): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:26)
E/FlutterSecureStoragePl( 9639): 	at ir.mytrx.mytrx2.MainActivity.configureFlutterEngine(:10)
E/FlutterSecureStoragePl( 9639): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(:178)
E/FlutterSecureStoragePl( 9639): 	at io.flutter.embedding.android.FlutterActivity.onCreate(:409)
E/FlutterSecureStoragePl( 9639): 	at android.app.Activity.performCreate(Activity.java:6178)
E/FlutterSecureStoragePl( 9639): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/FlutterSecureStoragePl( 9639): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
E/FlutterSecureStoragePl( 9639): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
E/FlutterSecureStoragePl( 9639): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/FlutterSecureStoragePl( 9639): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
E/FlutterSecureStoragePl( 9639): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterSecureStoragePl( 9639): 	at android.os.Looper.loop(Looper.java:135)
E/FlutterSecureStoragePl( 9639): 	at android.app.ActivityThread.main(ActivityThread.java:5910)
E/FlutterSecureStoragePl( 9639): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterSecureStoragePl( 9639): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/FlutterSecureStoragePl( 9639): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
E/FlutterSecureStoragePl( 9639): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by mr-mamali** [comment] 2020-07-10 09:06
Hint : 
i thing you have to change file RsaCipher18Implemention in your package.
in this file there is a function called " CreateKeys" , i thing it should change to something like this : 

    @SuppressLint("NewApi")
    @SuppressWarnings("deprecation")
    private void createKeys(Context context) throws Exception {
// Set English locale as default (workaround)
        Locale initialLocale = Locale.getDefault();
        setLocale(Locale.ENGLISH);
       // *********
        Calendar start = Calendar.getInstance();
        Calendar end = Calendar.getInstance();
        end.add(Calendar.YEAR, 25);

        KeyPairGenerator kpGenerator = KeyPairGenerator.getInstance(TYPE_RSA, KEYSTORE_PROVIDER_ANDROID);

        AlgorithmParameterSpec spec;

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            //noinspection deprecation
            spec = new android.security.KeyPairGeneratorSpec.Builder(context)
                    .setAlias(KEY_ALIAS)
                    .setSubject(new X500Principal("CN=" + KEY_ALIAS))
                    .setSerialNumber(BigInteger.valueOf(1))
                    .setStartDate(start.getTime())
                    .setEndDate(end.getTime())
                    .build();
        } else {
            KeyGenParameterSpec.Builder builder = new KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_DECRYPT | KeyProperties.PURPOSE_ENCRYPT)
                    .setCertificateSubject(new X500Principal("CN=" + KEY_ALIAS))
                    .setDigests(KeyProperties.DIGEST_SHA256)
                    .setBlockModes(KeyProperties.BLOCK_MODE_ECB)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_PKCS1)
                    .setCertificateSerialNumber(BigInteger.valueOf(1))
                    .setCertificateNotBefore(start.getTime())
                    .setCertificateNotAfter(end.getTime());

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                builder.setIsStrongBoxBacked(true);
            }

            spec = builder.build();
        }
        try {
            kpGenerator.initialize(spec);
            kpGenerator.generateKeyPair();
        } catch (StrongBoxUnavailableException se) {
            spec = new KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_DECRYPT | KeyProperties.PURPOSE_ENCRYPT)
                    .setCertificateSubject(new X500Principal("CN=" + KEY_ALIAS))
                    .setDigests(KeyProperties.DIGEST_SHA256)
                    .setBlockModes(KeyProperties.BLOCK_MODE_ECB)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_PKCS1)
                    .setCertificateSerialNumber(BigInteger.valueOf(1))
                    .setCertificateNotBefore(start.getTime())
                    .setCertificateNotAfter(end.getTime())
                    .build();
            kpGenerator.initialize(spec);
            kpGenerator.generateKeyPair();
        }
        // Reset default locale
        setLocale(initialLocale);
    }


and add this function too 👍

    /**
     * Sets default locale.
     */
    private void setLocale(Locale locale) {
        Locale.setDefault(locale);
        Resources resources = context.getResources();
        Configuration config = resources.getConfiguration();
        config.locale = locale;
        resources.updateConfiguration(config, resources.getDisplayMetrics());
    }

**Comment by mr-mamali** [comment] 2020-07-10 11:46
I found same issue about this problem and fixed PR , so i will close this issue . We are waiting for releasing this simple solution !
Tnx

**Comment by iassal** [comment] 2020-07-12 01:02
Just for reference, duplicate of https://github.com/mogol/flutter_secure_storage/issues/131

**Comment by juliansteenbakker** [comment] 2021-07-29 07:32
A fix has been merged in #132.

**Closed by juliansteenbakker** 2021-07-29 07:32 UTC
