### ISSUE TITLE
Can't run flutter test due to MissingPluginException in flutter_secure_storage

### ISSUE THREAD

**Issue by frazer84** [mogol/flutter_secure_storage#136] opened 2020-06-08 09:41 UTC
All flutter tests that run code containing calls to the flutter_secure_storage fails like this:

```
username@computername SampleApp % flutter test
00:01 +0 -1: /Users/username/git/SampleApp/test/sample_test.dart: Get token [E]                                       
  MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
  package:flutter/src/services/platform_channel.dart 157:7  MethodChannel._invokeMethod
```

I have tried most suggestions from other issues posted here that relates to this error (but no one mentioned tests specifically) like removing and reinstalling the plugin, running `pub cache repair` etc.

flutter doctor -v:
```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.97, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-4.0.pre.97 at /Users/danielzarins/Applications/flutter
    • Framework revision f32039bd64 (14 hours ago), 2020-06-07 15:38:01 -0400
    • Engine revision f38a197945
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 48b4528a44)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danielzarins/Library/android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/danielzarins/Library/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • B08E6BF7-B520-4E94-8724-8CB681BA5EF8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

**Comment by connlaoi** [comment] 2020-06-08 17:02
Upgrading from v1.12.13+hotfix.9 (Windows) to channel stable, or anything after v1.12.13+hotfix.9 causes my application to start throwing Missing Plugin Exceptions. 

If you need an urgent solution, rolling back with 'flutter version 1.12.13+hotfix.9' should resolve the error in my experience. I have been reviewing the related issues for about 4 weeks now and have not seen a clear understanding to what is causing the error.

**Comment by olivierbrand** [comment] 2020-06-18 13:37
The issue happens when building on Stable 17.3 (Mac). I have live customers that are randomly experiencing it. It is also the only plugin that behaves like this. I am thinking of removing it for now as not production ready.

**Comment by iassal** [comment] 2020-06-23 19:08
@olivierbrand Check https://github.com/mogol/flutter_secure_storage/issues/131 
If the users' locale is in an RTL language, this exception is triggered. Is this the case for you?

**Comment by olivierbrand** [comment] 2020-06-23 20:04
@iassal No. We use English. We ended up removing the plugin and saving for now in the non-secure storage, the risk for us is minimal and way better than have random issues in production caused by this missingpluginexception

**Comment by tabula-rasa** [comment] 2020-06-29 07:49
Having the same issue on android emulator v 9.0, api 28

**Comment by matejthetree** [comment] 2020-07-21 14:20
for me happens as well

**Comment by connlaoi** [comment] 2020-07-21 19:03
My issues were resolved by ensuring that the MainActivity.kt contained the following:

```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

Specifically, I was missing the "GeneratedPluginRegistrant.registerWith(flutterEngine);" line. I'm not sure how this happened, perhaps a build issue, or a flutter migration issue. But adding this line completely resolved the MissingPluginException for me.

I mostly test on Android and have not encountered this error on iOS, however, the similar file for iOS (which may run into similar issues) is AppDelegate.swift and the code to add would be "GeneratedPluginRegistrant.register(with: self)". Add this line just before "return super.application(...)".

Hopefully this helps resolve some issues.

**Comment by matejthetree** [comment] 2020-07-21 19:05
Thank you

**Comment by wilyanto** [comment] 2021-02-01 18:34
After few hours of surfing. Finally **SOLVED** for me. Here is what I found out.

If you are calling `flutter_secure_storage` (or any packages) method in background service (as example, when you are using notification `onBackgroundMessage`). This exception occurred because usually our plugin registered at `main.dart` in foreground, but if we are calling our plugin's method in background we need to manually registered our plugin in our `app/src/main/[kotlin/java]/.../Application.[java or kt]`.

Inside the Application.java or Application.kt

<img width="992" alt="image" src="https://user-images.githubusercontent.com/53255602/106501831-2cb93600-64f6-11eb-8169-3468272a6fec.png">

After done that, do `flutter run` again. Hope it helps!

**Comment by ykone** [comment] 2021-03-25 07:10
My problem is solved and I think it is a compatibility issue between plugins. I created a new project and added the plugins one by one. Arrived at the flutter_barcode_scanner: ^1.0.2 plugin the error appeared. So I just removed it and my app works fine with version 4.1.0 of flutter_secure_storage
Hope this helps other people.

**Comment by juliansteenbakker** [comment] 2021-07-29 09:27
I'm closing this in favor of #152

**Closed by juliansteenbakker** 2021-07-29 09:27 UTC
