### ISSUE TITLE
Unable to write to secure storage after updating the package from 4.2.0 to 4.2.1 (ANDROID)(RELEASE APK)

### ISSUE THREAD

**Issue by pratikbaid3** [mogol/flutter_secure_storage#272] opened 2021-08-03 07:33 UTC
Code:
```
final storage = new FlutterSecureStorage();
    await storage.write(key: "SecureToken", value: token.toString());
```
Error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
```

**Comment by juliansteenbakker** [comment] 2021-08-03 07:44
Please tell me which Android version and device you are using. Also, can you post the output of `flutter doctor -v`?

**Comment by pratikbaid3** [comment] 2021-08-03 07:49
Device:
```
One Plus Nord: Android 10
```
Flutter Doctor:
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3 20E232 darwin-arm, locale
    en-IN)
    • Flutter version 2.2.2 at /Users/pratikbaid/Developer/flutter
    • Framework revision d79295af24 (8 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pratikbaid/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • AC2001 (mobile) • 1ad657f3 • android-arm64  • Android 10 (API 29)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 11.3 20E232 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 92.0.4515.107```

**Comment by pratikbaid3** [comment] 2021-08-03 07:52
```
compileSdkVersion 30
minSdkVersion 19
targetSdkVersion 30
```

**Comment by juliansteenbakker** [comment] 2021-08-04 06:04
I have tried it on an emulator, but for me it works just fine in release mode. Do you have any other device to test it with?

**Comment by juliansteenbakker** [comment] 2021-08-09 06:49
I am closing this as duplicate of #152

**Closed by juliansteenbakker** 2021-08-09 06:49 UTC
Labels: bug

**Comment by Hesamedin** [comment] 2021-12-01 22:02
If you are testing on an emulator make sure to stop your app, first. Then re-run your project.
