### ISSUE TITLE
2 exceptions preventing use

### ISSUE THREAD

**Issue by TheCarpetMerchant** [mogol/flutter_secure_storage#444] opened 2022-08-29 17:03 UTC
I am getting these two exceptions in production :
`java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference`
`java.lang.SecurityException: Could not decrypt value. decryption failed`

When trying to read from the the storage.
This is of course extremely problematic, as I'm read values during the app's startup. It's preventing users from using the app at all.

What's going wrong here ?

**Comment by ostk0069** [comment] 2022-09-07 01:50
Same thing here.
`NullPointerException
Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference`

**Comment by henry2man** [comment] 2022-09-07 08:45
Possible duplicate of #380 ?

**Comment by TheCarpetMerchant** [comment] 2022-09-07 15:20
I'll be trying out the latest workaround mentioned in #380 then.

**Comment by juliansteenbakker** [comment] 2024-08-13 19:49
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 19:49 UTC
