### ISSUE TITLE
Do more people see an increase in issues on Samsung Galaxy S21 5G devices?

### ISSUE THREAD

**Issue by PieterAelse** [mogol/flutter_secure_storage#642] opened 2023-10-26 09:38 UTC
Starting around October 10 we're seeing an issue on some/all versions of Samsung Galaxy S21 5G devices (e.g. Galaxy S21 Ultra 5G, Galaxy S21 5G, Galaxy S21+ 5G) for our app in the field.

The issue results in users having to setup their app again, every time they open the app (so very annoying user experience, also receiving bad reviews on it). We have a strong suspicion the issue is related to use of this `flutter_secure_storage` package, or it's underlying used encryption.

But looking at the date the issues started and the devices that are impacted we also have a strong suspicion the issue is related to a recent Samsung Galaxy S21 5G update. Looking at your updates here (S21 5G: https://doc.samsungmobile.com/sm-g991b/xeo/doc.html, and S21 Ultra 5G: https://doc.samsungmobile.com/sm-g998b/dbt/doc.html) we see there were security updates for these devices around the day the issue started.

Do other apps/users of this package also experience a spike of issues in the field?

**Comment by lberaldodev** [comment] 2023-10-26 12:40
Hi @PieterAelse, how can I test it? And could you share your [flutter_secure_storage] version?

**Comment by jehhxuxu** [comment] 2023-10-27 12:38
Same here =/

<img width="1082" alt="Screenshot 2023-10-27 at 09 37 56" src="https://github.com/mogol/flutter_secure_storage/assets/27310692/b341ad8d-ebf4-41c5-9998-4e76e1d0276f">

**Comment by Politta** [comment] 2023-10-29 22:13
We are also experiencing the same issue in our app. Has anyone found an workaround/solution for it yet?

**Comment by OlegShNayax** [comment] 2023-10-30 08:13
We have the same issue!

**Comment by tobinharris** [comment] 2023-10-31 22:03
We think we have this issue too, it's killing us as paying subscribers are losing their ID's and so the app thinks they're non-paying 🤦

**Comment by Politta** [comment] 2023-10-31 22:05
The workaround we told our users is to uninstall and reinstall the app, that makes the issue go away.
However I don't think that's a great solution, would be best to be able to detect that something changed within the flutter_secure_storage library 🤔

**Comment by PieterAelse** [comment] 2023-11-22 12:46
@lberaldodev  Like also mentioned in the related issue #541, we (and others) don't know a good way to reproduce the issue. Do you happen to have any updates for us? (or for issue #541 )

**Comment by jhoffmann-macomptafr** [comment] 2024-01-10 20:22
Same issue here...

**Comment by juliansteenbakker** [comment] 2024-08-13 20:44
Im closing this as duplicate of #354

**Closed by juliansteenbakker** 2024-08-13 20:44 UTC
