### ISSUE TITLE
flutter_secure_storage does not work on Windows.

### ISSUE THREAD

**Issue by astudilloalex** [mogol/flutter_secure_storage#379] opened 2022-03-09 16:05 UTC
Hello, the package show a error when try launch on Windows.

**Platform:** Windows
**Package version:** 5.0.2

This is my pubspec.yaml file:

```
name: pharmacy_billing_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  http: ^0.13.4
  responsive_design: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
```
Just declare the package, I'm not using it yet but I'm getting the following error.
```
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
[D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp]()(6,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [[D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]()]
Exception: Build process failed.
Exited (sigterm)
```

![image](https://user-images.githubusercontent.com/48831301/157480476-ab171ab1-cb25-4ed1-8ccf-d4504e416cd5.png)

The software works fine if I remove the dependency from my pubspec.yaml.

**Comment by astudilloalex** [comment] 2022-04-23 19:56
Help with this error

> Hello, the package show a error when try launch on Windows.
> 
> **Platform:** Windows **Package version:** 5.0.2
> 
> This is my pubspec.yaml file:
> 
> ```
> name: pharmacy_billing_system
> description: A new Flutter project.
> 
> publish_to: 'none' 
> 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.16.1 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_secure_storage: ^5.0.2
>   get: ^4.6.1
>   google_fonts: ^2.3.1
>   http: ^0.13.4
>   responsive_design: ^0.0.21
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   lint: ^1.8.2
> 
> flutter:
>   uses-material-design: true
> ```
> 
> Just declare the package, I'm not using it yet but I'm getting the following error.
> 
> ```
> Launching lib\main.dart on Windows in debug mode...
> lib\main.dart:1
> [D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp]()(6,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [[D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]()]
> Exception: Build process failed.
> Exited (sigterm)
> ```
> 
> ![image](https://user-images.githubusercontent.com/48831301/157480476-ab171ab1-cb25-4ed1-8ccf-d4504e416cd5.png)
> 
> The software works fine if I remove the dependency from my pubspec.yaml.

**Comment by jbrechbuehl** [comment] 2022-04-30 01:21
I have the same issue

**Comment by jbrechbuehl** [comment] 2022-04-30 01:35
You need to install [[Visual Studio 2022 Community](https://visualstudio.microsoft.com/vs)] as explained here: https://docs.flutter.dev/get-started/install/windows

**Comment by astudilloalex** [comment] 2022-05-01 02:40
> You need to install [[Visual Studio 2022 Community](https://visualstudio.microsoft.com/vs)] as explained here: https://docs.flutter.dev/get-started/install/windows

I have installed Visual Studio, the app work correctly in Windows if delete the package, when add package the app breaks

**Comment by brookman** [comment] 2022-05-11 08:49
I have the same error which this package. Visual Studio and "Desktop development with C++" are installed and in general Windows builds for Flutter do work.

**Comment by mibi2007** [comment] 2022-05-20 10:36
Hi, I also have this issue, I'm using VSCode with Flutter 3.0.0 and updated extension, the Windows build works fine, but after adding the package flutter_secure_storage my app stop working and show the same message above.

**Comment by ViniciusLima** [comment] 2022-06-01 16:57
Install the individual components of 'atlstr.h' as shown in the video:
https://www.youtube.com/watch?v=Lq3SllRv7a8

If you have bad UTF-8 issues, go to:
https://github.com/flutter/flutter/issues/102451#issuecomment-1124651845

**Comment by TreyThomas93** [comment] 2022-06-05 14:48
> Install the individual components of 'atlstr.h' as shown in the video: https://www.youtube.com/watch?v=Lq3SllRv7a8
> 
> If you have bad UTF-8 issues, go to: [flutter/flutter#102451 (comment)](https://github.com/flutter/flutter/issues/102451#issuecomment-1124651845)

This worked for me. Thanks man!

**Comment by ijaspreetsinghh** [comment] 2022-09-22 07:31
> You need to install [[Visual Studio 2022 Community](https://visualstudio.microsoft.com/vs)] as explained here: https://docs.flutter.dev/get-started/install/windows

Moving to VS 2022 worked for me, Thanks man

**Comment by nridwan** [comment] 2022-12-14 06:49
I successfully run the app after adding this in "Visual Studio Build Tools 2022" installation.
Open Visual Studio Installer, click modify in existing installation, see optional items in right panel
![image](https://user-images.githubusercontent.com/10008414/207525396-730c6047-1013-4e4b-aad7-4c3489f7cc54.png)

**Comment by DoumanAsh** [comment] 2023-03-01 07:12
`C++ ATL` is enough btw
`C++ MFC` is not required to build

**Comment by Glitched-Manual** [comment] 2024-04-07 09:48
I was able to patch the package within VS Code.

**Comment by Glitched-Manual** [comment] 2024-04-07 11:33
Alright. I have linked an example with the solution in the README.md for ease of access.
https://github.com/Glitched-Manual/quick_secure_storage_patch

**Comment by Glitched-Manual** [comment] 2024-04-07 11:33
# quick_secure_storage_patch

#install flutter_secure_storage:

```
flutter pub add flutter_secure_storage
```

# add import

```
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
```

# run windows desktop build
- project will fail  (thats fine)


- Run commands to copy files to where they are needed

```
cp "windows/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_windows/windows/*.*" "windows/flutter/ephemeral/"
```

```
cp "windows/flutter/ephemeral/atls.lib" "build/windows/x64/plugins/flutter_secure_storage_windows/"
```

# run windows desktop build (twice) ((yes run 2 times))
- And you are done.

**Comment by Glitched-Manual** [comment] 2024-04-07 11:46
The issue is only is easy to solve.

What is happening:

On getting the `fatal error C1083: Cannot open include file: 'atlstr.h'`.

The builder just not able to find the package CPP files needed.

After installing flutter_secure_storage.
with:

``` cmd
flutter pub add flutter_secure_storage
```

The files needed are located in `/your_project_path/windows/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_windows/windows/`

**Comment by waqadArshad** [comment] 2024-06-10 02:44
> The issue does not take long to solve. What is happening:
> 
> On getting the `fatal error C1083: Cannot open include file: 'atlstr.h'`.
> 
> The builder just not able to find the package CPP files needed.
> 
> After installing flutter_secure_storage. with:
> 
> ```batchfile
> flutter pub add flutter_secure_storage
> ```
> 
> The files needed are located in `/your_flutter_project_path/windows/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_windows/windows/`
> 
> The `.cpp` , `.h` , `.dll`, and `.lib` files need to be copied to `/your_flutter_project_path/windows/flutter/ephemeral/`
> 
> Then `'atls.lib'` needs to be copied to the location of the `flutter_secure_storage_windows_plugin.vcxproj` file: `/your_flutter_project_path/build/windows/x64/plugins/flutter_secure_storage_windows/`
> 
> Then running the debugger builds and object file that is needed.
> 
> Then you are in the clear.
> 
> *******This Issue Can be Closed *******

I don't know why but I do not have these files in there either.

**Comment by juliansteenbakker** [comment] 2024-08-13 19:46
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 19:46 UTC

**Comment by zacharyw** [comment] 2024-10-30 13:50
@waqadArshad You still need to install visual studio 2022 community edition (ensure you go to optional packages and install the c++ atl package like someone else screenshotted above) AND I had to install "Desktop development with C++" workload.
