### ISSUE TITLE
Weird issue where for iOS only

### ISSUE THREAD

**Issue by curtis2101** [mogol/flutter_secure_storage#614] opened 2023-09-15 12:37 UTC
There is an issue where the top line of a storeAndOverwrite function is saved and able to be read when the app is running. But on restart of the app the top line that was written could not be found at all. This happens only on IOS and to fix this I Have added a future delay for now. So in this example without a delay the biometric preference would read while the app is running and its just been saved but on restart it would not show but all the other keys and values would be.
Future<void> storeAndOverwrite(SecureStorageContent storedContent) async {
    await Future.delayed(const Duration(
        milliseconds:
            200)); //do not remove this line seems to be a ios issue where the top line is not stored
    await storage.write(
        key: Dummy.biometricPreference,
        value: storedContent.biometricPreference);
    await storage.write(
        key: Dummy.soundPreference,
        value: storedContent.soundPreference);
    await storage.write(
        key: Dummy.vibrationPreference,
        value: storedContent.vibrationPreference);
    await storage.write(key: LegacyConstants.email, value: storedContent.email);
    await storage.write(
        key: Dummy.password, value: storedContent.password);
    await storage.write(
        key: Dummy.accessToken, value: storedContent.accessToken);
    await getStoredContent();
  }

**Comment by harshitwe360** [comment] 2023-10-04 12:19
I have updated with new IOS versions, after that I had got same issue, String type data is not get stored. but its working fine in android, even in IOS debug mode not working in release mode. 

Any idea whats going wrong..!

**Comment by MatthewJones517** [comment] 2023-10-23 20:49
I am having the same issue with 9.0.0. Took me forever to track down that this plugin was the problem. Issue only occurs in iOS release builds. Nowhere else.

**Comment by MatthewJones517** [comment] 2023-10-24 15:39
After digging in a bit deeper, I found that this was caused by doing a read immediately after doing a write. We weren't fully awaiting the save, so only part of the value made it in to secure storage before we pulled it out. 

I'm not saying that's everyone's problem, but it's something to check for those that stumble on this thread in the future.

**Comment by Kijacode** [comment] 2023-10-29 13:29
so @MatthewJones517  , have you solve it ??

**Comment by cheymos** [comment] 2024-01-18 14:33
Is the problem still relevant?

**Comment by aswinranjith-iouring** [comment] 2024-05-21 07:35
any update on this?

**Comment by juliansteenbakker** [comment] 2024-05-21 09:50
Version 9.2.1 fixed a race condition issue with read/write, which could be this issue. It would be great if someone can check if this version still has this issue.

**Comment by juliansteenbakker** [comment] 2024-08-13 20:13
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 20:13 UTC
