### ISSUE TITLE
Runtime error for web 5.0

### ISSUE THREAD

**Issue by tmtong** [mogol/flutter_secure_storage#320] opened 2021-10-25 05:14 UTC
~/Documents/flutter_secure_storage/flutter_secure_storage/example$ flutter build web --web-renderer html --release

~/Documents/flutter_secure_storage/flutter_secure_storage/example$ sudo cp -r ./build/web/* ~/Documents/www/

![image](https://user-images.githubusercontent.com/38814587/138637956-684ce891-d3ff-4fbc-95d8-057d13244111.png)

I got in the browser console
Uncaught TypeError: Cannot read property 'generateKey' of undefined

**Comment by juliansteenbakker** [comment] 2021-11-12 15:23
I advise testing in another browser. I am closing this for now. If this issue still exists please comment.

**Comment by henry2man** [comment] 2021-11-23 08:57
> I advise testing in another browser. I am closing this for now. If this issue still exists please comment.

I'm facing also this issue in my deployment using latest 5.0.2 version.

The issue is present **only when the app is built**, not in development mode.

**Comment by juliansteenbakker** [comment] 2021-11-23 08:58
@henry2man which browser are you using?

**Comment by henry2man** [comment] 2021-11-23 08:59
Stable Chrome 96.0.4664.55 w/ MacOS Monterrey on M1

The issue is also present in Safari

**Comment by henry2man** [comment] 2021-11-23 09:06
> @henry2man which browser are you using?

@juliansteenbakker Do you want me to do a specific test with my setup to see if we can have a minimum case from which to test? Any example or test of the plugin?

**Comment by juliansteenbakker** [comment] 2021-11-23 09:13
After some searching it seems that webCrypto **only** works when the site is running **HTTPS** or **localhost**. How are you running your test?

Source: https://github.com/ipfs/js-ipfs/issues/964#issuecomment-325269476

**Comment by henry2man** [comment] 2021-11-23 09:29
That's the key. For now I'm developing so I'm using localhost && HTTP only.

I think this should be documented in README.md, isn't it?

Thank you very much.

**Comment by juliansteenbakker** [comment] 2021-11-23 09:56
Yes indeed, thanks for the verification !

**Comment by juliansteenbakker** [comment] 2021-11-23 09:58
I have added the note in the readme doc.

**Closed by juliansteenbakker** 2021-11-23 09:58 UTC
