### ISSUE TITLE
OperationError when calling `read()` on web

### ISSUE THREAD

**Issue by shroff** [mogol/flutter_secure_storage#381] opened 2022-03-25 08:00 UTC
I'm getting the following error when calling `read()` on web, only if the key exists in storage. It works fine if the key does not exist. Calling `containsKey()` returns the correct value and does not produce this error.
```
Error: OperationError


    at Object.createErrorWithStack (http://localhost:5000/dart_sdk.js:5080:12)
    at Function._throw (http://localhost:5000/dart_sdk.js:20337:18)
    at Function.throwWithStackTrace (http://localhost:5000/dart_sdk.js:20334:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:40851:18)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:40714:13)
    at http://localhost:5000/dart_sdk.js:36191:9
```

This seems to be triggered from invoking the `callback` function in the following block:
```
    static _scheduleImmediateWithPromise(callback) {
      dart.addAsyncCallback();
      dart.global.Promise.resolve(null).then(() => {
        dart.removeAsyncCallback();
        callback();
      });
    }
```

I'm running Chromium 99.0.4844.82 on Arch Linux

Any thoughts on what this could be caused by?

NB: `OperationError` seems to be a DomException constant.

**Comment by pedro371** [comment] 2022-03-25 13:26
I'm encountering the same error on macOS.

**Comment by SlavisDEV** [comment] 2022-03-29 08:17
+1

**Comment by duck-dev-go** [comment] 2022-03-30 15:57
+1 I also have this on web

**Comment by duck-dev-go** [comment] 2022-03-30 18:30
From what I can see the error is in

flutter_secure_storage_web.dart:152

```
  Future<String?> _decryptValue(
    String? cypherText,
    Map<String, String> options,
  ) async {
    if (cypherText == null) {
      return null;
    }

    final parts = cypherText.split(".");

    final iv = base64Decode(parts[0]);
    final algorithm = _getAlgorithm(iv);

    final decryptionKey = await _getEncryptionKey(algorithm, options);

    final value = base64Decode(parts[1]);

    final decryptedContent = await js_util.promiseToFuture<ByteBuffer>(
      crypto.decrypt(
        _getAlgorithm(iv),
        decryptionKey,
        Uint8List.fromList(value),
      ),
    );

    final plainText = utf8.decode(decryptedContent.asUint8List());

    return plainText;
  }

```

Might this be relevant?

https://stackoverflow.com/questions/68160151/how-to-fix-this-operationerror-error-when-decrypting-data-with-crypto-api

**Comment by momrak** [comment] 2022-04-08 07:44
I get this error as well. Have any of you found out why, or a fix?

This is not happening on all `read()`s in my case. I't is one of the keys that constantly fail. I have tried using dummy values and the same values for the two keys, but it is always only one of them that fails. 

Also, how do you get a thorough stack trace like that? All I see in my logs when doing `catch(e,s)` and printing those are the `OperationError`

**Comment by duck-dev-go** [comment] 2022-04-08 12:25
I used the webserver command

`flutter run -d web-server`

And then I got a thorough stack trace. I think this is a issue with the way the decrypting is done, and I myself do not have much experience with encryption and know that it is easy to make mistakes if not done properly.

**Comment by FrankNanninga** [comment] 2022-04-09 18:23
I had the same issue on macOS using the Web version.

My mistake was not using async / await properly - after adding "await" to **ALL** read / write functions, everything was working fine.

Hope that helps!

**Comment by duck-dev-go** [comment] 2022-04-12 09:57
@momrak were you storing a JWT by any chance,? We are. I wonder if the decryption fails for certain characters. Thanks for the tip!

**Comment by shroff** [comment] 2022-04-12 11:08
> @momrak were you storing a JWT by any chance,? We are. I wonder if the decryption fails for certain characters. Thanks for the tip!

JWTs are Base64url encoded and separated by '.'s, so they should not contain any characters other than [A-Za-z0-9-_.]. It would be very strange if this character set is unsuitable for storage.

**Comment by momrak** [comment] 2022-04-12 12:05
@duck-dev-go Yes, this was the case for an access token JWT. But I tried changing to simple strings as well just to see if that helped, but I still got then problem when doing that. Hope combining them might work for you as well :)

**Comment by duck-dev-go** [comment] 2022-04-15 22:32
I can confirm that storing it as json works. I wonder why. Maybe you can't store multiple things? Anyway thanks @momrak !

**Comment by duck-dev-go** [comment] 2022-04-15 22:40
I think what is happening is that when you want to store multiple values it overrides the encryption key. So that is why it works as json. Because the name of the encryption key will stay the same in localstorage.

**Comment by AndreiMisiukevich** [comment] 2022-05-12 01:10
Faced this issue too. For some reason, it occurs only when I run the app on localhost.

**Comment by apetroaeiandrei** [comment] 2022-05-17 09:27
I found a workaround for this issue. Make sure you're not writing to the storage concurrently. Just await for each operation.

Consider having this function.
```
 Future<void> _writeString(String key, String value) async {
    const storage = FlutterSecureStorage();
    await storage.write(key: key, value: value);
  }
```
Calling it like this will produce read errors further on

```    
_writeString("key1", "data");
_writeString("key2", "some other data");
```

but awaiting for them will work just fine
```
await _writeString("key1", "data");
await _writeString("key2", "some other data");

```

**Comment by paulFlow33** [comment] 2022-08-08 15:33
#427 Hi guys, it looks like you are using the package for the web. Can you please explain some facets to me, I have to implement a web app and times are tight. You would do me a great pleasure if you give me examples and maybe explain the bare minimum. I'm finding it wrong with the documentation because it doesn't exist.

**Comment by thinkingatoms** [comment] 2022-08-14 18:56
thank you [apetroaeiandrei](https://github.com/apetroaeiandrei)!

i added the synchronized package https://pub.dev/packages/synchronized, then wrapped my writes with: 
```
    await _lock.synchronized(() async {
      await _prefs!.write(key: key, value: value);
    });
```

operationerror issues gone!

**Comment by Thioby** [comment] 2023-07-25 10:56
Encoding object as json works, thx @momrak

**Comment by juliansteenbakker** [comment] 2024-08-13 19:46
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 19:46 UTC

**Comment by fauzan123-sudo** [comment] 2024-08-25 23:55
I'm still experiencing errors, and haven't found a single solution

**Comment by Archais** [comment] 2024-10-15 10:22
Hi @juliansteenbakker. Can confirm that this issue is still prevalent as of [v9.2.2](https://github.com/mogol/flutter_secure_storage/releases/tag/v9.2.2). On the web, the package currently seems to store a single encryption key for all key-value pairs instead of generating a unique key per each key-value pair. This key is regenerated each time a different key-value pair is written to storage, which causes a generic `OperationError` to throw when attempting to read any value other than the most recently written one.

The more recent issue #773 illustrates the same problem.

For anyone viewing this, the current workaround is to map all of your values then store the map as a single JSON-encoded string.

```dart
/// Sample code for storing (or updating) the suggested JSON encoded value.
void writeToStorage(Map<String, Object> values) async {
    final storage = const FlutterSecureStorage();
    final details = await storage.read(key: "details") ?? "";
    final Map<String, dynamic> detailsMap = details.isNotEmpty ? jsonDecode(details) : {};

    values.forEach((String key, Object value) => detailsMap[key] = value);
    storage.write(key: "details", value: jsonEncode(detailsMap));
}
```

A potential solution might be to apply the workaround to the value encryption keys instead of the values themselves. In other words, the encryption key handling would change from:

```json
{
    "key": "key_value",
    "field 1": "some_encrypted_value",
    "field 2": "some_other_encrypted_value"
}
```

To:
```json
{
    "key": "{\"field 1\":\"key_value\",\"field 2\":\"other_key_value\"}",
    "field 1": "some_encrypted_value",
    "field 2": "some_other_encrypted_value"
}
```

If I get the chance, I'd be happy to have a closer look at this and contribute a solution.

**Comment by juliansteenbakker** [comment] 2025-01-15 20:41
Does anyone have any code as to how to reproduce this? I tried reproducing this myself, but i am unable to.
