### ISSUE TITLE
Flutter secure storage data is getting cleared on IOS when the app is in background more than 2 hr.

### ISSUE THREAD

**Issue by yogesh-asu** [mogol/flutter_secure_storage#223] opened 2021-04-06 14:48 UTC
Hi guys,

We have kept the app running in background and after 2 hour when we resumed it after that the data got deleted.
-This issue is occurring only on release build (TestFlight or app store).

**Comment by kolhozz** [comment] 2021-04-12 15:42
do you use notifications?

**Comment by elouiestudent** [comment] 2021-04-21 18:39
We are also getting the same issue - any flutter secure storage data manipulation in the background does not persist.

**Comment by yogesh-asu** [comment] 2021-04-23 09:05
> Did you get notifications before?

Yes @kolhozz , We are using notifications

**Comment by mogol** [comment] 2021-04-26 11:30
Looks like it's not a bug, but a well-known feature. Please check this [stackoverflow](https://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background) question or [apple dev forum](https://developer.apple.com/forums/thread/7961).

You could use this enum to tweak IOS Accessibility: https://github.com/mogol/flutter_secure_storage/blob/d8aeaee6ed2898e622f3ec83e2c75af41294f22e/lib/flutter_secure_storage.dart#L148-L168

**Comment by loonix** [comment] 2021-06-24 08:12
That's a good point, made me go search for more info on the actual code and I made a PR with doc changes:
https://github.com/mogol/flutter_secure_storage/pull/244/files

**Comment by juliansteenbakker** [comment] 2021-07-27 21:04
The readme is updated, so i'm closing this for now.

**Closed by juliansteenbakker** 2021-07-27 21:04 UTC

**Comment by AndreiMisiukevich** [comment] 2022-04-30 23:46
Hey folks, should this be implemented for macos as well?

**Comment by nicolasvahidzein** [comment] 2024-04-23 23:56
Hello @mogol how can set the enum you mentioned to avoid this issue, i have been running after this bug for 8 months now. Thanks for your help.

**Comment by nicolasvahidzein** [comment] 2024-04-24 00:00
@mogol they mention in the SO article you referenced that this key should be set:

kSecAttrAccessibleAfterFirstUnlock 

where and how do we set it please?

**Comment by loonix** [comment] 2024-04-24 07:33
@nicolasvahidzein just read my last post

```dart
final options = IOSOptions(accessibility: IOSAccessibility.first_unlock);
await storage.write(key: key, value: value, iOptions: options);
```
