### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by Aggie85** [mogol/flutter_secure_storage#603] opened 2023-09-01 22:28 UTC
After a recent upgrade of flutter_securre_storage, I keep getting the following error under Windows... 

Launching lib\main.dart on Windows in debug mode...
√  Built build\windows\runner\Debug\sandis_list.exe.
Connecting to VM Service at ws://127.0.0.1:49857/9uCr3Nyrbfs=/ws
flutter: Failed to decrypt data: Error 0x00000000: Failure on CryptUnprotectData() Delete corrupt file: c:\users\shane\appdata\roaming\tanstaaflsoftware\sandis_list\flutter_secure_storage.dat
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Error 0x00000000: Failure on CryptUnprotectData()
#0      DpapiJsonFileMapStorage.load.<anonymous closure> (package:flutter_secure_storage_windows/src/flutter_secure_storage_windows_ffi.dart:234:11)
#1      using (package:ffi/src/arena.dart:124:31)
#2      DpapiJsonFileMapStorage.load (package:flutter_secure_storage_windows/src/flutter_secure_storage_windows_ffi.dart:209:19)
<asynchronous suspension>
#3      FlutterSecureStorageWindows.readAll (package:flutter_secure_storage_windows/src/flutter_secure_storage_windows_ffi.dart:113:17)
<asynchronous suspension>
#4      AppPreferencesFlutterSectureStorage.readAll (package:sandis_list/app_preferences_flutter_secure_storage.dart:50:12)
<asynchronous suspension>
#5      AppGlobalObjects.initialize (package:sandis_list/app_global_objects.dart:108:10)
<asynchronous suspension>
#6      main (package:sandis_list/main.dart:48:3)
<asynchronous suspension>

I haven't changed this part of my code in almost 6 months!

Any idea on how to fix or what could have changed?

All the best,

Aggie85

**Comment by ReinRaus** [comment] 2023-10-18 20:21
This error is caused by multiple writes to the storage.  

Сode example to reproduce the error (need to quickly scroll the list):

```dart
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

late final FlutterSecureStorage storage;

void main() {
  storage = const FlutterSecureStorage();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    var controller = ScrollController();
    controller.addListener(
      () => storage.write(key: "key", value: "${controller.offset}"),
    );

    return MaterialApp(
      title: 'Scroll quickly to see the bug.',
      home: Scaffold(
        body: ListView(
          controller: controller,
          children: [for (int i = 0; i < 100; i++) Text("$i")],
        ),
      ),
    );
  }
}
```

**Comment by stan-at-work** [comment] 2023-10-31 11:47
> This error is caused by multiple writes to the storage.
> 
> Сode example to reproduce the error (need to quickly scroll the list):
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> 
> late final FlutterSecureStorage storage;
> 
> void main() {
>   storage = const FlutterSecureStorage();
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     var controller = ScrollController();
>     controller.addListener(
>       () => storage.write(key: "key", value: "${controller.offset}"),
>     );
> 
>     return MaterialApp(
>       title: 'Scroll quickly to see the bug.',
>       home: Scaffold(
>         body: ListView(
>           controller: controller,
>           children: [for (int i = 0; i < 100; i++) Text("$i")],
>         ),
>       ),
>     );
>   }
> }
> ```

@mogol plz fix asap

**Comment by juliansteenbakker** [comment] 2024-08-13 20:14
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Closed by juliansteenbakker** 2024-08-13 20:14 UTC

**Comment by stephankopp** [comment] 2025-01-15 07:15
I got the same issue with 10.0.0-beta.4

**Comment by nini22P** [comment] 2025-01-19 08:20
Same problem in 9.2.4

**Comment by Arley011** [comment] 2025-02-17 11:38
I faced the same issue on `9.2.2`

**Comment by Anotherjez** [comment] 2025-04-29 17:53
Same issue on 10.0.0-beta.4 @juliansteenbakker
