### ISSUE TITLE
Datas are not removed when app is uninstalled - I0S

### ISSUE THREAD

**Issue by aswinsubhash** [mogol/flutter_secure_storage#765] opened 2024-08-09 06:29 UTC
When an app is uninstalled on iPhone, the data stored once is not removed from the phone local storage
Why???

**Comment by muhamedRadwan** [comment] 2024-08-10 13:31
any solution to that?

**Comment by koji-1009** [comment] 2024-08-11 00:30
Duplicate of https://github.com/mogol/flutter_secure_storage/issues/125

**Comment by juliansteenbakker** [comment] 2024-08-13 20:39
Please see this fix https://github.com/mogol/flutter_secure_storage/issues/88#issuecomment-613168109

**Closed by juliansteenbakker** 2024-08-13 20:39 UTC
