### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')

### ISSUE THREAD

**Issue by elcolie** [mogol/flutter_secure_storage#355] opened 2022-01-15 07:07 UTC
Background:
I am trying to authenticate myself to next page

I run same code on Mac 12.1 has no problem. I can read/write token to disk
Then I deploy to Ubuntu Linux by `flutter build web`
`await storage.write(key: 'jwt', value: cleanedToken["token"]);` raises an error
Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')

Step to reprofuce
1. Install flutter_secure_storage: ^5.0.2
2. flutter build web on Linux
3. http-server build/web
3. await storage.write(key: 'jwt', value: cleanedToken["token"]);

Expected result:
Be able to write token to disk

As is:
Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')

**Comment by Andrflor** [comment] 2022-01-15 07:41
Duplicate of  #320

You are serving the app over http instead of https
It's written in the README.md:

### Important notice for Web
flutter_secure_storage only works on HTTPS or localhost environments. [Please see this issue for more information.](https://github.com/mogol/flutter_secure_storage/issues/320#issuecomment-976308930)

 [Here](https://github.com/mogol/flutter_secure_storage/blob/develop/README.md#important-notice-for-web) is the corresponding README section.
I guess it's README all in caps for a reason :rofl:

**Closed** 2022-01-15 11:54 UTC
